{{- if .Values.eePullSecret.manage }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ee-pull-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: ee-pull-secret
  dataFrom:
  - extract:
      key: {{ .Values.eePullSecret.key }}
{{- end }}
